[color]
# Nord Theme
    color0="#2E3440"
    color1="#3B4252"
    color2="#434C5E"
    color3="#4C566A"
    color4="#D8DEE9"
    color5="#E5E9F0"
    color6="#ECEFF4"
    color7="#8FBCBB"
    color8="#88C0D0"
    color9="#81A1C1"
    color10="#5E81AC"
    color11="#BF616A"
    color12="#D08770"
    color13="#EBCB8B"
    color14="#A3BE8C"
    color15="#B48EAD"
    
    dimblack="#373e4d"
    dimred="#94545d"
    dimgreen="#809575"
    dimyellow="#b29e75"
    dimblue="#68809a"
    dimmagenta="#8c738c"
    dimcyan="#6d96a5"
    dimwhite="#aeb3bb"


[font]
    name="VictorMono NF"
    namealt="VictorMono NFP"
    size=10
    sizealt=10

[xft]
    dpy=120

[dunst]

[rofi]

[cwm]

[bspwm]

[sxhkd]

[alacritty]

[emacs]
