(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(auto-save-interval 200)
 '(auto-save-list-file-prefix "~/.emacs.d/auto-save-list/.saves-")
 '(auto-save-timeout 20)
 '(backup-by-copying t)
 '(backup-directory-alist '(("." . "~/.emacs.d/backup")))
 '(bookmark-default-file "~/.emacs.d/bookmark")
 '(cursor-type '(hbar . 2))
 '(delete-old-versions t)
 '(evil-undo-system 'undo-fu)
 '(evil-want-fine-undo t)
 '(find-file-visit-truename t)
 '(history-delete-duplicates t)
 '(history-length 50)
 '(indicate-buffer-boundaries nil)
 '(inhibit-buffer-choice t)
 '(inhibit-compacting-font-caches t t)
 '(inhibit-startup-echo-area-message '(user-login-name))
 '(inhibit-startup-screen t)
 '(iso-transl-char-map nil t)
 '(kept-new-versions 5)
 '(kept-old-versions 5)
 '(kill-ring-max 50)
 '(make-backup-files t)
 '(make-pointer-invisible t)
 '(menu-bar-mode nil)
 '(mouse-wheel-inhibit-click-time 0)
 '(mouse-wheel-progressive-speed nil)
 '(mouse-wheel-scroll-amount '(1 ((shift) . 1) ((meta)) ((control) . text-scale)))
 '(nano-font-family-monospaced "VictorMono Nerd Font")
 '(nano-font-family-proportional "Victor Mono")
 '(nano-font-size 10)
 '(org-babel-load-languages '((shell . t) (emacs-lisp . t) (C . t) (ocaml . t)))
 '(org-log-done 'time)
 '(org-log-done-with-time t)
 '(package-selected-packages '(use-package))
 '(prefer-coding-system 'utf-8)
 '(recentf-mode nil)
 '(ring-bell-function 'ignore)
 '(scroll-bar-mode nil)
 '(scroll-step 1)
 '(select-enable-clipboard t)
 '(set-cursor-color "black")
 '(set-default-coding-systems 'utf-8)
 '(set-keyboard-coding-system 'utf-8)
 '(set-language-environment "English")
 '(set-terminal-coding-system 'utf-8)
 '(straight-use-package-by-default t)
 '(tool-bar-mode nil)
 '(tooltip-mode nil)
 '(tramp-backup-directory-alist "~/.emacs.d/tramp")
 '(undo-limit 67108864)
 '(undo-outer-limit 1073741824)
 '(undo-strong-limit 134217728)
 '(user-full-name "Tracnac")
 '(user-mail-address "tracnac@devmobs.fr")
 '(visible-bell nil)
 '(widget-image-enable nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
